spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbboot
    username: root
    password: 1234
  jpa:
   hibernate:
     ddl-auto: update
   show-sql: true


